# Generated by Django 4.2.16 on 2024-11-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=100)),
                ('profileImage', models.ImageField(upload_to='profile_images/')),
                ('summary', models.TextField()),
                ('jobTitle', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('workDates', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('graduationDate', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('projects', models.TextField()),
                ('certifications', models.TextField()),
                ('awards', models.TextField()),
                ('hobbies', models.TextField()),
            ],
        ),
    ]
