# Generated by Django 4.2.16 on 2024-11-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='Resume',
        ),
    ]
