# Generated by Django 4.2.16 on 2024-11-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
