# Generated by Django 4.2.16 on 2024-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='hard_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Hard Skills'),
        ),
        migrations.AddField(
            model_name='resume',
            name='soft_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Soft Skills'),
        ),
    ]
